services:
  - type: web
    name: my-flavourtie-app
    env: docker
    dockerfilePath: ./backend/Dockerfile
    rootDir: backend    # ← 반드시 backend 폴더 안에서 Dockerfile을 읽도록 지정
    region: oregon
    plan: free

    # Dockerfile 자체가 의존성 설치/서버 실행을 책임지므로, buildCommand를 빈 문자열로 남겨도 됩니다.
    # (env: docker일 때 render에서는 buildCommand가 무시됩니다.)
    buildCommand: ""

    # 컨테이너가 실행될 때 Render가 이 커맨드를 무시하지만, render.yaml에 남겨놔도 됨.
    startCommand: ""

    envVars:
      - key: RENDER_DISK_MOUNT_PATH
        value: /srv/disk_data
      - key: PORT
        value: "10000"

    disks:
      - name: my-persistent-disk
        mountPath: /srv/disk_data
        sizeGB: 1

    autoDeploy: yes
    branch: main
